version: '3.8'

services:
  ocr-api:
    build: .
    container_name: ocr-service
    ports:
      - "4000:4000"
    environment:
      - OCR_API_PORT=4000
      - OCR_API_HOST=0.0.0.0
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    volumes:
      - ocr-logs:/app/logs
      - ocr-temp:/app/temp
    restart: unless-stopped
    mem_limit: 2g
    cpus: '0.7'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge

volumes:
  ocr-logs:
  ocr-temp: